---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'My 3 tier app: core'

Parameters:

  VpcCidr:
    Type: String
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  
  Environment:
    Type: String
    AllowedValues: ['prod', 'test']

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod"]

Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, 'vpc']]
        - Key: Env
          Value: !Ref Environment
      
  MyFrontendSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
        #CidrBlock: !Select [ 0, !Ref FrontendSubnetCidr ]
        CidrBlock: !Select [0, !Cidr [ !Ref VpcCidr, 12, 8 ]]
        VpcId: !Ref MyVpc
        Tags:
          - Key: Name
            Value: !If [IsProd, "IsProdFound", "IsProdNotfound"]

Outputs:
  MyVpcId:
    Value: !Ref MyVpc
    Export:
      Name: MyVpcId

  MyFrontendSubnetId:
    Value: !Ref MyFrontendSubnet1
    Export:
      Name: MyFrontendSubnetId