---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'My 3 tier app'

Parameters:

  VpcCidr:
    Type: String
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  
  FrontendSubnetCidr:
    Type: CommaDelimitedList


  # MiddlewareSubnetCidr1:
    # Type: String
    # AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

    
  # DatabaseSubnetCidr1:
    # Type: String
    # AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

    
  Environment:
    Type: String
    AllowedValues: ['prod', 'test']

Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, 'vpc']]
        - Key: Env
          Value: !Ref Environment
      
  MyFrontendSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
        CidrBlock: !Select [ 1, !Ref FrontendSubnetCidr ]
        VpcId: !Ref MyVpc

#  MyFrontendSubnet2:
#    Type: AWS::EC2::Subnet
#    Properties:
#        CidrBlock: !Select [1, FrontendSubnetCidr]
#        VpcId: !Ref MyVpc

#  MyFrontendSubnet3:
#    Type: AWS::EC2::Subnet
 #   Properties:
#        CidrBlock: !Select [2, FrontendSubnetCidr]
#        VpcId: !Ref MyVpc        
        
