AWSTemplateFormatVersion: '2010-09-09'
Description: 'My 3 tier app: webtier'

Resources:
  WebTierSg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "LB SG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
      VpcId: !ImportValue MyVpcId

  WebTierTg:
    Type: "AWS:ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue MyVpcId
      Tags:
        - Key: Env
          Value: !Ref Environment
          Key: Name
          Value: !Join ["-", [ !Ref Environment, !Ref "AWS::StackName", "lb-tg" ] ]

  WebTierLbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WebTierLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref WebTierTg
